my_list = list(range(20))
#third argu is step (aka add count)
print(my_list[::2])
print(my_list[2::2])
print(my_list[::-1])
print(my_list[::-2])
print("Oklahoma"[::2])
print("Oklahoma"[::-1])
#if you neg index have to swap positons of first two intgers
print(my_list[8:1:-1])
print(my_list[-1])