<?php

//handles input
function greeting_menu(){
    $items = array();
    $items['hello_friend'] = array(
        'title' => "Hello Friend!",
        'page callback' => 'say_hello',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items['goodbye'] = array(
        'title' => "Goodbye Friend!",
        'page callback' => 'say_goodbye',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK                                                                                                             ,
    );
    return $items;
}
//handles output
function say_hello(){
    return '<p> Hello My Dear Friend! </p>';
}

function say_goodbye(){
    return "<p> Goodbye My Dear Friend! Come Back Soon! </p>";
}

function greeting_user_login(){
    $_GET['destination'] = 'hello_friend';
}

function greeting_user_logout(){
    $_GET['destination'] = 'goodbye';
}
//don''t php tag clo{se tag for drupal