# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='MultipleChoiceQuestions',
            fields=[
                ('question_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='courses.Question')),
                ('shuffle_answers', models.BooleanField(default=False)),
            ],
            bases=('courses.question',),
        ),
        migrations.RenameModel(
            old_name='Answers',
            new_name='Answer',
        ),
    ]
